const colors = {
  light: {
    text: "#0d1117",
    tint: "#0A84FF",
    background: "#F2F2F7",
    foreground: "#0d1117",
    card: "#FFFFFF",
    cardForeground: "#0d1117",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EEF8",
    secondaryForeground: "#1C1C1E",
    muted: "#EBEBF0",
    mutedForeground: "#8E8E93",
    accent: "#E8EEF8",
    accentForeground: "#0A84FF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#F2F2F7",
    success: "#30D158",
    warning: "#FF9F0A",
    videoDownloader: "#0A84FF",
    audioExtractor: "#FF6B35",
    videoConverter: "#BF5AF2",
    videoCutter: "#FF3B30",
    videoCompressor: "#34C759",
    mergeVideos: "#FF9F0A",
    addSubtitles: "#5AC8FA",
    thumbnailDownloader: "#FF2D55",
    surfaceElevated: "#FFFFFF",
  },
  dark: {
    text: "#F2F2F7",
    tint: "#0A84FF",
    background: "#000000",
    foreground: "#F2F2F7",
    card: "#1C1C1E",
    cardForeground: "#F2F2F7",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#F2F2F7",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#2C2C2E",
    accentForeground: "#0A84FF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#1C1C1E",
    success: "#30D158",
    warning: "#FF9F0A",
    videoDownloader: "#0A84FF",
    audioExtractor: "#FF6B35",
    videoConverter: "#BF5AF2",
    videoCutter: "#FF3B30",
    videoCompressor: "#34C759",
    mergeVideos: "#FF9F0A",
    addSubtitles: "#5AC8FA",
    thumbnailDownloader: "#FF2D55",
    surfaceElevated: "#1C1C1E",
  },
  radius: 14,
};

export default colors;
